### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by vrnvorona** [Extended-Thunder/remote-content-by-folder#6]
I tried default (.* for allow and spam/deleted etc for blocked) with reverse checkbox. Tried both allow and not allow in thunderbird settings, it doesn't matter. If I allow it in settings - content is loaded everywhere, if not allowed - content is not loaded anywhere.
Even .* without reverse checkbox doesn't work.

Using 102.2.2 (64-bit) windows version

**Comment by jikamens** [comment]
II'm using it every day and it's working fine for me ;-), so let's try to get to the bottom of what's different for you.

Please open the Add-ons and Themes page in Thunderbird, click the gear icon, and select "Check for Updates", then if anything gets updated, quit and restart Thunderbird. Then please check what version of Remote Content By Folder you're using by clicking on it in the add-on listing and scrolling down to where it shows the version. Post the version in a comment here.

Please also post a screenshot of the preferences page for the add-on. If either the allow or block regexp is too long to show fully in the text box, then please cut and paste the full value here.

Finally, after Thunderbird has been running for a bit and you've received at least a few new email messages, open the error console (Tools -> Developer Tools -> Error Console), enter "remote-content" in the filter box, and copy about ten lines of the displayed log messages into a comment here so I can see a sample of what the extension is logging as it works.

**Comment by vrnvorona** [comment]
Oh, last thing did the trick. I tested it using old emails. New ones work perfectly. It's not obvious that it is supposed to work only on new e-mails. Sorry for that (also maybe add it to readme then?)

Also, thanks for very quick reply.

**Comment by jikamens** [comment]
>(also maybe add it to readme then?)

The README.md in this repository says, "...in messages added to folders (usually, but not always, newly received message)" in the first paragraph.

The home page on addons.thunderbird.net says, "Note that the settings you specify for Remote Content By Folder are only applied when the message first arrives. If you change the settings Thunderbird won't go back and re-evaluate whether to display images for existing messages, and if you move or copy a message from one folder to another Thunderbird won't re-evaluate whether to display images based on the target folder."

I.e., I believe this behavior is already fully documented.
